apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lifehacker-backend-deploy
  name: lifehacker-backend-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: lifehacker-backend-deploy
  type: ClusterIP
status:
  loadBalancer: {}